from enum import Enum

from .streams import StreamHandle

class Verbosity(Enum):
    QUIET = ...
    BRIEF = ...
    VERBOSE = ...
    DEBUG = ...
    TRACE = ...

class Emitter:
    def __init__(
        self,
        verbosity: Verbosity,
        log_filepath: str,
        greeting: str,
        *,
        docs_base_url: str | None = None,
        streaming_brief: bool = False,
    ) -> None: ...
    @classmethod
    def log_filepath_from_name(cls, app_name: str) -> str: ...
    def get_verbosity(self) -> Verbosity: ...
    def set_verbosity(self, new: Verbosity) -> None: ...
    def debug(self, text: str) -> None: ...
    def trace(self, text: str) -> None: ...
    def progress(self, text: str, *, permanent: bool = False) -> None: ...
    def message(self, text: str) -> None: ...
    def warning(self, text: str, prefix: str = "WARNING: ") -> None: ...
    def ended_ok(self) -> None: ...
    def open_stream(self, prefix: str | None) -> StreamHandle: ...
    def set_prefix(self, prefix: str) -> None: ...
    def clear_prefix(self) -> None: ...
