from typing import BinaryIO

from typing_extensions import Self

class StreamHandle(BinaryIO):
    def __enter__(self) -> Self: ...
    def __exit__(self, *_args: object) -> None: ...
    def fileno(self) -> int: ...
