settings:
  components:
    - Craft CLI
  labels:
    - "Type: Bug"
    - "Type: Enhancement"
    - "Type: Spike"
    - "Type: Research"
  # Adds a comment with the JIRA ID
  add_gh_comment: true
  # Reflect changes on JIRA
  sync_description: true
  # Comments are synced from Github to JIRA
  # Nothing goes from JIRA to Github
  sync_comments: true
  # epic_key: "MTC-296"
  jira_project_key: "CRAFT"
  status_mapping:
    opened: Untriaged
    closed: done
  label_mapping:
    "Type: Enhancement": Story
    "Type: Bug": Bug
    "Type: Spike": Spike
    "Type: Research": Epic
